'\" t
.\"     Title: youtube_dlhelper
.\"    Author: Sascha Manns <Sascha.Manns@mailbox.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 10/07/2017
.\"    Manual: User Commands
.\"    Source: Ruby
.\"  Language: English
.\"
.TH "YOUTUBE_DLHELPER" "1" "" "Ruby" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
youtube_dlhelper \- A Youtube Downloadhelper
.SH "SYNOPSIS"
.HP \w'\fByoutube_dlhelper\fR\ 'u
\fByoutube_dlhelper\fR YoutubeUrl
                
.HP \w'\fByoutube_dlhelper\fR\ 'u
\fByoutube_dlhelper\fR http://www\&.youtube\&.com/watch?v=aHjpOzsQ9YI
                
.SH "DESCRIPTION"
.PP
\fByoutube_dlhelper\fR
helps by downloading Music from Youtube\&. You are running the program inside the command line with a Youtube URL\&. Then it asks for a group name or interpreters name\&. Now it creates a Subfolder inside your Musicdirectory\&. Then it makes a OGG or MP3 from the downloaded file and moves it to the folder\&.
.SH "BUGS"
.PP
Place Bugs on: https://bugs\&.launchpad\&.net/youtube\-dlhelper\&.
.SH "SEE ALSO"
.PP
.PP
Feature Requests: https://blueprints\&.launchpad\&.net/youtube\-dlhelper\&.
.RS 4
.RE
.PP
Ask a question: https://answers\&.launchpad\&.net/youtube\-dlhelper\&.
.RS 4
.RE
