language: ruby
rvm:
  - 2.2.0
  - 2.2.1
  - 2.2.2
  - 2.2.3

dist: trusty
sudo: false

os:
  - linux

env:
  global:
    - JRUBY_OPTS=-Xcext.enabled=true
    - CI=true
    - TRAVIS=true
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8

before_install:
    - gem install bundler
    - sudo apt-get update
    - sudo apt-get install software-properties-common -y
    - sudo apt-get install youtube-dl libav-tools libavcodec-extra autoconf -y
    - sudo apt-get install xsltproc docbook-xsl docbook-xml
    - ./autogen.sh && make

after_success:
    - CI=true TRAVIS=true coveralls --verbose

notifications:
  email:
    - Sascha.Manns@mailbox.org
