language: ruby
rvm:
  - 2.2.0
  - 2.3.0
  - 2.4.0
  - 2.4.1
  - ruby-head # MRI head
  - jruby # JRuby RVM default
  - jruby-9.1.12.0 # JRuby 9k series
  - jruby-head # JRuby Head
  - rbx-2 # Rubinius stable

cache: bundler

matrix:
  allow_failures:
  - rvm: jruby
  - rvm: jruby-head
  - rvm: ruby-head

dist: trusty
sudo: false

os:
  - linux

env:
  global:
    - JRUBY_OPTS=-Xcext.enabled=true
    - CI=true
    - TRAVIS=true
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8

before_install:
    - gem install bundler
    - sudo apt-get update
    - sudo apt-get install software-properties-common -y
    - sudo apt-get install libavcodec-extra -y
    - pushd ~/bin
    - wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-64bit-static.tar.xz
    - tar xvfJ ffmpeg-git-64bit-static.tar.xz
    - popd
    - bundle install
    - sudo chmod 755 ~/.rvm/gems/*/gems/youtube-dl.rb/vendor/bin/youtube-dl

after_success:
    - CI=true TRAVIS=true coveralls --verbose

notifications:
  email:
    - Sascha.Manns@mailbox.org
