# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "bundler", "~>1.15"
gem "parseconfig", "~>1.0"
gem "streamio-ffmpeg", "~>3.0"
gem "rainbow", "~>2.2"
gem "addressable", "~>2.5"
gem "notifier", "~>0.5"
gem "youtube-dl.rb", "~>0.3.1.2016"
gem "xdg", "~>2.2"

gem "coveralls", "~>0.8", :group => [:development, :test]
gem "hoe", "~>3.16", :group => [:development, :test]
gem "hoe-bundler", "~>1.3", :group => [:development, :test]
gem "hoe-manns", "~>1.6", :group => [:development, :test]
gem "hoe-rubygems", "~>1.0", :group => [:development, :test]
gem "hoe-version", "~>1.2", :group => [:development, :test]
gem "rake", "~>12.1", :group => [:development, :test]
gem "rdoc", "~>5.1", :group => [:development, :test]
gem "rspec", "~>3.6", :group => [:development, :test]

# vim: syntax=ruby
